sass:
  style: compressed
  sass_dir: _scss

navigation:
  - title: Home
    url: index.html
  - title: How it works
    url: how-it-works.html
  - title: Installation
    url: installation.html
  - title: Transition
    url: transition.html
  - title: Events
    url: events.html
  - title: Views
    url: views.html
  - title: Cache
    url: cache.html
  - title: Prefetch
    url: prefetch.html
  - title: API
    url: docs/
    external: true
  - title: Demos
    url: demos.html
  - title: FAQ
    url: faq.html
  - title: Various
    url: various.html

